version: 1
formatters:
    simple:
        format: '%(asctime)s - %(name)s:%(funcName)s:%(lineno)d - %(levelname)s - %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    root_log_file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: log
        maxBytes: 10485760 #10MB
        backupCount: 3
    asset_trader_log_file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: asset_trader.log
        maxBytes: 10485760 #10MB
        backupCount: 3
    asset_trader_debug_file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: asset_trader.debug
        maxBytes: 10485760 #10MB
        backupCount: 3
    autoassets_debug_file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: autoassets.debug
        maxBytes: 10485760 #10MB
        backupCount: 3
    tda_debug_file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: tda.debug
        maxBytes: 10485760 #10MB
        backupCount: 3
loggers:
    root:
        level: INFO
        handlers: [console]
    asset_trader:
        level: DEBUG
        handlers: [asset_trader_debug_file,root_log_file]
    autoassets:
        level: DEBUG
        handlers: [autoassets_debug_file,root_log_file]
        propagate: yes
    tda:
        level: DEBUG
        handlers: [tda_debug_file,root_log_file]
        propagate: yes
